spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
    initialization-mode: always
    initialize: true
    continue-on-error: true
    schema: classpath:/schema.sql
    data: classpath:/data.sql
#
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa

#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: create-drop

