spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
    initialization-mode: always
    initialize: true
    continue-on-error: true
    schema: classpath:/schema.sql
    data: classpath:/data.sql

mybatis:
  type-aliases-package: com.antonio.example.mybatis.model
  mapper-locations: classpath*:**/mappers/*Mapper.xml


