INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE ) VALUES ('PRODUTO 1', 'PRIMEIRO PRODUTO', 165.5);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE ) VALUES ('PRODUTO 2', 'SEGUNDO PRODUTO', 65.0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE ) VALUES ('PRODUTO 3', 'TERCEIRO PRODUTO', 5.0);
