INSERT INTO CATEGORY (NAME, DESCRIPTION ) VALUES ('CATEGORIA 1', 'PRIMEIRA CATEGORIA');
INSERT INTO CATEGORY (NAME, DESCRIPTION ) VALUES ('CATEGORIA 2', 'SEGUNDA CATEGORIA' );
INSERT INTO CATEGORY (NAME, DESCRIPTION ) VALUES ('CATEGORIA 3', 'TERCEIRA CATEGORIA' );

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID ) VALUES ('PRODUTO 1', 'PRIMEIRO PRODUTO', 165.5, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID ) VALUES ('PRODUTO 2', 'SEGUNDO PRODUTO', 65.0, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID ) VALUES ('PRODUTO 3', 'TERCEIRO PRODUTO', 5.0, 1);

