-- PRODUTO
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT(
   ID serial PRIMARY KEY,
   NAME VARCHAR (255) UNIQUE NOT NULL,
   DESCRIPTION VARCHAR (255) NOT NULL,
   PRICE REAL NOT NULL
);

--INSERT INTO PRODUCT VALUES (1, 'PRODUTO 1', 'PRIMEIRO PRODUTO', 165.5);
--INSERT INTO PRODUCT VALUES (2, 'PRODUTO 2', 'SEGUNDO PRODUTO', 65.0);
