-- CATEGORIA
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY(
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR (255) UNIQUE NOT NULL,
   DESCRIPTION VARCHAR (255) NOT NULL
);

-- PRODUTO
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT(
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR (255) UNIQUE NOT NULL,
   DESCRIPTION VARCHAR (255) NOT NULL,
   PRICE REAL NOT NULL,
   CATEGORY_ID SERIAL NOT NULL,

   FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);

